### ISSUE TITLE
use protocol 2

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/postgrex_wal#1]

**Comment by json2008** [comment]
- [x] 将原有的 `protocol 1` 的 `decoder` 代码，修改适配到 `protocol 2`
- [x] 完成 `protocol 2`所新增加的事件消息的解码。
- [ ] 添加相应的测试。

**Comment by json2008** [comment]
@fahchen 

待 Pull request #15 `approval`后，此 Pr 即可提交上来。

**Comment by fahchen** [comment]
方便兼容 protocol 1 就做，不方便就只支持 protocol 2 及以上

**Comment by json2008** [comment]
在 #24 中，已经解决掉了。
